---
title: "R Notebook"
output: html_document
---

```{r load packages, echo = F, message = FALSE, warning = FALSE}
library(tidyverse); library(tidylog); library(janitor); library(sf); library(kableExtra); library(scales); library(spatstat); library(skimr)
library(gridExtra); library(knitr); library(echarts4r)
#library(extrafont)

source("A:/OneDrive/GIS/Programming/Github/plotting/theme_clch.R")
source("A:/OneDrive/GIS/Programming/Github/plotting/outputs_clch.R")
mtheme <- "A:/OneDrive/GIS/Programming/Github/plotting/theme_echarts2.json"
```

```{r echo = F, message = FALSE, warning = FALSE}
df <- state.x77 %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column("State")



p <- df %>% 
  e_charts(x = State) %>% # initialise and set x
  e_line(serie = Population) %>%
  e_x_axis(splitLine = list(show = FALSE)) %>% #,
          # axisLine = list(lineStyle = list(color = "red"))) %>% 
  e_tooltip()

p %>% e_theme_custom(mtheme)




```


```{r echo = F, message = FALSE, warning = FALSE}

v <- LETTERS[1:10]
matrix <- data.frame(
  x = sample(v, 300, replace = TRUE), 
  y = sample(v, 300, replace = TRUE), 
  z = rnorm(300, 10, 1),
  stringsAsFactors = FALSE
) %>% 
  dplyr::group_by(x, y) %>% 
  dplyr::summarise(z = sum(z)) %>% 
  dplyr::ungroup()
#> `summarise()` regrouping output by 'x' (override with `.groups` argument)

p <- matrix %>% 
  e_charts(x) %>% 
  e_heatmap(y,z) %>% 
 e_visual_map(
    z, # scale to z
    inRange = list(color = c("#440154",
            "#481567",
            "#482677",
            "#453781",
            "#404788",
            "#39568c",
            "#33638d",
            "#2d708e",
            "#287d8e",
            "#238a8d",
            "#1f968b",
            "#20a387",
            "#29af7f",
            "#3cbb75",
            "#55c667",
            "#73d055",
            "#95d840",
            "#b8de29",
            "#dce319",
            "#fde725")), # scale colors
    #dimension = 4, # third dimension 0 = x, y = 1, z = 2, size = 3, color = 4
    #bottom = 300 # padding to avoid visual maps overlap
  )

p %>% e_theme_custom(mtheme)

```
```{r}
quakes %>% 
  e_charts(long) %>% 
  e_geo(
    roam = TRUE,
    boundingCoords = list(
      c(185, - 10),
      c(165, -40)
     )
  ) %>% 
  e_scatter_gl(lat, depth) %>% 
  e_visual_map()
```

